### ISSUE TITLE
Support for HubSpot's oAuth2.0 URL and new Endpoints

### ISSUE THREAD

**Issue by Soben** [ryanwinchester/hubspot-php#108]
The URL for HubSpot's oAuth 2.0 handling is api.hubspot.com ... and you show an argument for base_url but it does not appear to be used anywhere in your src/ folder for override of the base_url...

Also, after authenticating the user, I get a CODE that I need to get refresh and authentication tokens from the api at api.hubspot.com/v1/tokens, which isn't an endpoint you offer accessibility to.

**Comment by Soben** [comment]
Re: the URL... I could just be an idiot and it still is api.hubapi.com ... but the /token endpoint remains elusive.

**Comment by siremi** [comment]
Hi,
I had the same issue. I just added support for that here: https://github.com/ryanwinchester/hubspot-php/pull/110

**Comment by Soben** [comment]
Thanks Siremi, giving that a whirl now

**Comment by ryanwinchester** [comment]
thanks
