### ISSUE TITLE
no possibility to provide hs_context

### ISSUE THREAD

**Issue by vertexvaar** [ryanwinchester/hubspot-php#159]
Hi @ryanwinchester 

i want to provide the `hs_context` on form data submission but i can only pass the form data to the `Forms::submit()` method.
The context is described in https://developers.hubspot.com/docs/methods/forms/submit_form
Can you please add the possibility to send the context along with the form data?
Thank you very much!

**Comment by erikrorstrom** [comment]
@vertexvaar As far as I can see the hs_context is part of the form data. So if you just append hs_context array to your form fields, you should be fine.

**Comment by vertexvaar** [comment]
You are right, thank you.
After scrutinizing my code i found out that i was `url_encode`-ing the json context data :man_facepalming:
