### ISSUE TITLE
Do you already know about HTTPlug and PSR18 ?

### ISSUE THREAD

**Issue by shulard** [ryanwinchester/hubspot-php#164]
Hello !

We are using your lib on our project and when I checked your dependencies I saw that you rely directly on Guzzle.

The goal of the [HTTPlug](http://httplug.io/) project and the new [PSR-18](https://www.php-fig.org/psr/) is to decouple from the HTTP client when creating a library. Because if I use a different HTTP adapter in my project than yours I finally have multiple implementation of the same feature in my dependencies.

If you are open to integrate that logic I can work on a PR :smile:. If not, can you explain why ?

Thanks

**Comment by ryanwinchester** [comment]
You can pass in a different client, it just defaults to Guzzle.

**Comment by shulard** [comment]
Of course you can but Guzzle6 is still in your direct dependencies so it can cause compatibility issues. No problem if you don't want to integrate that part.

**Comment by DavidGarciaCat** [comment]
I agree with @shulard - Guzzle is a required dependency that might cause a conflict if another dependency has a requirement on another Guzzle's version.

Isn't it possible to make it optional and add it as a suggestion, or implement the HttPlug and PSR18 so all devs can use any HTTP adapter?
