### ISSUE TITLE
WordPress wrapper?

### ISSUE THREAD

**Issue by eddr** [ryanwinchester/hubspot-php#172]
Hi, is there one? if not, can I use wrap your code, with permission?

Thanks

**Comment by gregrobson** [comment]
I haven't seen one. If you want to make one, then you can, just make sure you honour the license by keeping it as part of your wrapper.

https://github.com/ryanwinchester/hubspot-php/blob/master/LICENSE

As far as I know this means that any unmodified code that you use from here should be accompanied by a copy of the license.

**Comment by maximejobin** [comment]
What does a "WordPress wrapper" mean ? You can use this library in whatever PHP you'd like! That will surely imply so come though.

**Comment by ryanwinchester** [comment]
> Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Apache 2.0 license means free to use, without conditions. 👍

**Comment by tspesh** [comment]
You don't really need a wrapper.  Although it's not really ideal (or even doable) for some situations (certain managed hosting situations perhaps)? 

If you include the autoload.php in your wp-config.php or functions.php file, you'd have access to it throughout your app.  I'm using it this way now, in fact.

**Comment by eddr** [comment]
Thanks all

Yes, @tspesh, a plugin. Ended doing something simple like you've mentioned (-:
