### ISSUE TITLE
Do you plan to support guzzle v6?

### ISSUE THREAD

**Issue by rreynier** [ryanwinchester/hubspot-php#18]
Currently you require v5 of guzzle, 6 is the latest and greatest though :(

**Comment by fungku** [comment]
I haven't had time to play with anything. Are there any breaking changes?

**Comment by rreynier** [comment]
Don't actually know.  I ended up swapping my project over to v5 of guzzle and that worked fine.  The other components I had seemed to have no issue moving down to v5, which leads me to believe the changes are that large :)

**Comment by fungku** [comment]
I tried it with guzzle 6 and things dont work. will need to refactor some stuff

**Comment by ryanwinchester** [comment]
The `develop` branch should be working with Guzzle 6 now.

Re: 05f6d36dcde6f45acc68fb9f1e5ec0bacb60ca4f

**Comment by ryanwinchester** [comment]
Actually, I think there are a few kinks to work out still.

**Comment by ryanwinchester** [comment]
Got it working, we're getting an `stdClass` instead of an associateive `array` right now. check the readme on the develop branch for update on what that looks like.

**Comment by ryanwinchester** [comment]
FYI: `array access` is possible again now, too -- since 3322c285a6c35eb3a5da8679f98114dd08aa0356

**Comment by rreynier** [comment]
Cool, thank Ryan!
