### ISSUE TITLE
How do you map fields for deals->getRecentlyModified?

### ISSUE THREAD

**Issue by mackecm2** [ryanwinchester/hubspot-php#188]
I'm trying to call the deals->getRecentlyModified() method using the following code:

$a_week_ago = time() - 604800;

$response = $deals->getRecentlyModified([
    'limit'     => 100,
    'since'  => $a_week_ago 
]);

although I'm getting a http 200 response code back, I'm not getting any deals returned. I should be getting at least 100 deals if not more. What am I doing wrong?

**Comment by mackecm2** [comment]
Here's the full code:

$client = new Client(['key' => '.....-....-...-...-......']);

$deals = new Deals($client);
$a_week_ago = time() - 604800;

$response = $deals->getRecentlyModified([
    'limit'     => 100,
    'since'  => $a_week_ago 
]);

foreach ($response->deals as $deal) {
	echo "\n";
    echo sprintf(
        "Deal ID is %s %s." . PHP_EOL,
        $deal->properties->hs_object_id->value,
        $deal->properties->xtrf_quote_number->value
    );
	echo "\n";
}

**Comment by mackecm2** [comment]
and the response:

PHP Notice:  Undefined property: stdClass::$deals in /../hubspot-php/src/Http/Response.php on line 38
PHP Warning:  Invalid argument supplied for foreach() in /...php on line 42

**Comment by mackecm2** [comment]
Is nobody contributing to to this project any more?

**Comment by mjloreto** [comment]
I've been trying to do the same thing with **$hubspot->contactLists()->contacts('$id');** and im getting the same results as you, the aditional properties are not working for me unless i use them in **$hubspot->contacts()->all**

Please let me know if you find the way to do it. Thanks!

**Comment by mackecm2** [comment]
Got it in the end.

For my code, I had to switch 
foreach ($response->deals as $deal) {
for
foreach ($response->results as $deal) {
