### ISSUE TITLE
Create, Read, Update Company Fields with PHP 5.3

### ISSUE THREAD

**Issue by prashant-earth** [ryanwinchester/hubspot-php#28]
Hi,

We want to use Add, read, edit Company properties with HubSpot. We have PHP Version 5.3.
But I guess to modify company properties we need to use HubSpot V2 API, which is only supported on PHP Version >= 5.5.

Is there any way we can use HubSpot V1 API for updating company properties with PHP 5.3?
We do not want to update to PHP 5.5 as of now.

Please advice. Also suggest alternatives.

Thanks,
Prashant

**Comment by ryanwinchester** [comment]
The Companies API is on the `php53` branch now. The Company Properties API is not on any branch yet.

You will have to provide your own `HttpClient` for the `php53` branch.

> We do not want to update to PHP 5.5 as of now.

http://php.net/supported-versions.php By now you should probably skip 5.5 and go for 7.x :santa:
