### ISSUE TITLE
slash missing in endpoint

### ISSUE THREAD

**Issue by vilasbirajdar** [ryanwinchester/hubspot-php#31]
Starting slash (/) is missing in endpoint. Please fix this.
https://github.com/ryanwinchester/hubspot-php/blob/php53/src/Api/ContactProperties.php#L37

**Comment by ryanwinchester** [comment]
fixed. thanks

**Comment by vilasbirajdar** [comment]
Thanks @ryanwinchester

**Comment by andrew-kaslick** [comment]
Can this fix be applied to the php54-guzzle5 branch as well? Thanks!
https://github.com/ryanwinchester/hubspot-php/blob/php54-guzzle5/src/Api/ContactProperties.php#L36
