### ISSUE TITLE
Documentation need updating?

### ISSUE THREAD

**Issue by spingary** [ryanwinchester/hubspot-php#39]
Hi,

Now that the response is implementing PSR-7 ResponseInterface, does the README need to be updated?  Or am I retrieving the results incorrectly?

This seems to be the only way to access the data:
```
        $response = $hubspot->blogs()->all();
        $blogs = $response->getData();
        foreach ($blogs->objects as $blog) {
            echo($blog->name);
        }
```

Thank you,
Gary Wong

**Comment by ryanwinchester** [comment]
This is the [response from hubspot](https://api.hubapi.com/content/api/v2/blogs?hapikey=demo):

![](https://s3-us-west-2.amazonaws.com/ryanwinchester/screenshots/Screenshot+2016-01-21+18.30.05.png)

So you should be able to do:

```php
$response = $hubspot->blogs()->all();
foreach ($response->objects as $blog) {
    echo($blog->name);
}
```

**Comment by ryanwinchester** [comment]
This is the [raw response from hubspot](https://api.hubapi.com/content/api/v2/blogs?hapikey=demo):

![](https://s3-us-west-2.amazonaws.com/ryanwinchester/screenshots/Screen+Shot+2016-03-05+at+7.45.17+PM.png)

So you should be able to do either of these ways:

```php
$response = $hubspot->blogs()->all();

// PSR-7, something like:
$contents = $response->getBody()->getContents();
$blogs = $contents->objects;
foreach ($blogs as $blog) {
    echo($blog->name);
}

// That's annoying, so I added some convenience:

// Method to get data from response
$data = $response->getData();
foreach ($data->objects as $blog) {
    echo($blog->name);
}

// Property accessor
foreach ($response->objects as $blog) {
    echo($blog->name);
}
// Array access
foreach ($response['objects'] as $blog) {
    echo($blog->name);
}
```

**Comment by spingary** [comment]
I see - that makes sense.  I was just a bit confused by the examples in README (I believe that's pre-PSR7).

Thank you,
Gary
