### ISSUE TITLE
Iterate over results

### ISSUE THREAD

**Issue by geekdevs** [ryanwinchester/hubspot-php#43]
I am now upgrading from version `v0.9.7`  and I think something has broken on the lib regarding iterating over the results. 

Currently, if I run code like this it would give me 0 results.

```
        $count = 0;
        $resp = $hubSpotService->contacts()->all();
        foreach ($resp as $row) {
            ++$count;
        }

        echo $count; //outputs `0`
```

The only workaround for this I see is following (which looks ugly).

```
        $count = 0;
        $resp = $hubSpotService->contacts()->all()->toArray();
        foreach ($resp as $row) {
            ++$count;
        }

        echo $count; //outputs `3`
```

Is this an "official" way to iterate over results now? Previously (on v.0.9.7) both approaches would give me the same output.

**Comment by ryanwinchester** [comment]
Every request returns a PSR-7 response object, with a few helper methods I've added.

You should be able to do this:

```php
        $count = 0;
        $resp = $hubSpotService->contacts()->all();
        foreach ($resp->contacts as $row) {
            ++$count;
        }
```

or 

```php
        $count = 0;
        $resp = $hubSpotService->contacts()->all();
        foreach ($resp['contacts'] as $row) {
            ++$count;
        }
```

**Comment by geekdevs** [comment]
@ryanwinchester the problem is that responses are not always wrapped like that. E.g. `deals` endpoint does not add extra "deals" wrapper in response, but rather returns data directly.

**Comment by ryanwinchester** [comment]
Then that is a bug in Deals class

**Comment by geekdevs** [comment]
No it's not it just groups it under `results` on api response itself. 
Ok, nevermind this issue. I think this is correct, I just wanted to point out that behavior changed since previous versions and it was probably a bit more friendlier back then.

**Comment by ryanwinchester** [comment]
@geekdevs before, we didn't even get the status code from the response. It is now implementing a [standard response interface](http://www.php-fig.org/psr/psr-7/).

I tried to keep it as friendly as I could by using magic __get methods and also implementing array interfaces. But It's still a tradeoff for more flexibility.

**Comment by geekdevs** [comment]
@ryanwinchester yes I understand, this is good. It has become much better than it was.
