### ISSUE TITLE
RequestException causes catchable fatal error

### ISSUE THREAD

**Issue by raymondelooff** [ryanwinchester/hubspot-php#48]
RequestExceptions that are thrown by Guzzle are catched in Client.php on line 38. A response should be returned, however the given parameter to the Response constructor is a string instead of a ResponseInterface. This causes the following error:

**Catchable fatal error:** Argument 1 passed to Fungku\HubSpot\Http\Response::__construct() must implement interface Psr\Http\Message\ResponseInterface, null given, called in /.../vendor/fungku/hubspot-php/src/Http/Client.php on line 39 and defined in **/.../vendor/fungku/hubspot-php/src/Http/Response.php** on line **24**

**Comment by ryanwinchester** [comment]
Would appreciate input: https://github.com/ryanwinchester/hubspot-php/commit/20e725a4480b71838d0ab8e232a3113021264173#commitcomment-17734526

If I change that to just always re-throw instead, then it would mean less potential paths and checks...

**Comment by raymondelooff** [comment]
I think that's a great solution. Indeed less checking on the users' end when re-throwing an exception.
Thanks for the great work!

**Comment by ryanwinchester** [comment]
This will be fixed in 1.0.0-rc1 when I merge in the `refactor` branch
