### ISSUE TITLE
Folder is not conrect

### ISSUE THREAD

**Issue by StingNguyen** [ryanwinchester/hubspot-php#49]
File:
Factory.php

function __call($name, $arguments = null)
    {
        $resource = 'SevenShores\\Hubspot\\Resource\\' . ucfirst($name);
        return new $resource($this->client);
    }

`'SevenShores\\Hubspot\\Resource\\' . ucfirst($name);`

`Resource`

Folder??? 

`Resources`

**Comment by ryanwinchester** [comment]
thanks
