### ISSUE TITLE
Refreshing OAuth token

### ISSUE THREAD

**Issue by Spoowy** [ryanwinchester/hubspot-php#50]
Hey everybody,
First thanks for creating this awesome package.

Is there a function to refresh the OAuth token? I can get the whole thing set up but I will need to refresh the OAuth token for further use.

Thanks

**Comment by ryanwinchester** [comment]
@Spoowy currently, no... that is something you will have to handle yourself or with your own library, currently.

I can add a couple endpoints for that soon though.

**Comment by sc0ttkclark** [comment]
Are there any examples on using OAuth with this API?

**Comment by ryanwinchester** [comment]
No, I don't use oauth, so I haven't needed to do it. 

Currently you use this package with oauth token instead of an api key, but you will have to handle creating and refreshing the token on your own.

**Comment by Spoowy** [comment]
Well done, @ryanwinchester
