### ISSUE TITLE
Problem uploading file - request option issues?

### ISSUE THREAD

**Issue by bret-2600** [ryanwinchester/hubspot-php#56]
Hello!

Sorry if this is obvious.  I'm somewhat new to this.  My call to upload a file...

`$files->upload('/var/www/html/signed_documents/documents.zip');`

Is resulting the following error:

`PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request.' in /var/www/html/public/myproject/vendor/guzzlehttp/guzzle/src/Client.php:402`

Any suggestions?

**Comment by ryanwinchester** [comment]
I will have to look at this when I find some time.

**Comment by ryanwinchester** [comment]
This should have been fixed in https://github.com/ryanwinchester/hubspot-php/commit/06b9e78248b0746f0708caf16071ee0de8cf829a
