### ISSUE TITLE
How to handle error message that sends in response when contact creation failed?

### ISSUE THREAD

**Issue by p29892p** [ryanwinchester/hubspot-php#58]
Hi there,

When a contact insertion operation fails due to error such as Invalid property name, contact already existed, etc, it simply raising an exception. Is there any way to get error response that was sent from API. Here i added screen shot of the exception.

**Comment by ryanwinchester** [comment]
You had your API key in the screenshot, I removed it for you.

I will look at this issue tomorrow.

**Comment by p29892p** [comment]
Thank you @ryanwinchester

**Comment by ryanwinchester** [comment]
You can use `getStatusCode()` and `getReasonPhrase()` on the response.

The response implements PSR7, so here is some more info:  https://github.com/guzzle/guzzle/blob/master/docs/psr7.rst

Also:

 - https://github.com/php-fig/http-message/blob/master/src/ResponseInterface.php
 - https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php
