### ISSUE TITLE
Transactional Email API

### ISSUE THREAD

**Issue by cclass** [ryanwinchester/hubspot-php#60]
Hi Ryan,

Thanks for putting this together, it's been a huge help.

Any chance you'll be adding support for the [Transactional Email API](http://developers.hubspot.com/docs/methods/email/transactional_email/) anytime soon?

Thanks

Chris

**Comment by ryanwinchester** [comment]
Thanks, I am super busy and only add endpoints I need to use for work these days, but the endpoints are easy to add, so maybe someone who needs it will add it ;)

**Comment by cclass** [comment]
@ryanwinchester I actually went ahead and did this for the SingleSend API which is what I needed and it works great. I created #61 – happy to make any recommended changes to get this merged!

**Comment by ryanwinchester** [comment]
Cool! Thanks!
