### ISSUE TITLE
Webhooks API

### ISSUE THREAD

**Issue by lukevers** [ryanwinchester/hubspot-php#63]
Slightly busy right now which is why I'm opening an issue like the README says instead of doing it and then opening a pull request, but I might get to this at some point if no one else does.

http://developers.hubspot.com/docs/methods/webhooks/webhooks-overview

**Comment by devdrops** [comment]
Hi @lukevers! I've found this issue through the DigitalOcean Hacktoberfest but I didn't understood what exactly has to be done here. Could you please provide more details on this subject? Thanks in advance!

**Comment by ryanwinchester** [comment]
@devdrops if you look in src/Resources that correspond to a Hubspot API.

So what I think @lukevers would need is a new Resource class that corresponds to the Webhooks

you can look in `src/Resources` for examples, they are pretty easy to create. and read the Contributing.md as well! 

cheers

**Comment by bennychan** [comment]
Added webhooks api
