### ISSUE TITLE
Travis CI v1.0.0-rc.4 fails

### ISSUE THREAD

**Issue by sstoyanov7** [ryanwinchester/hubspot-php#74]
Hi Ryan,

Travis CI [v1.0.0-rc.4 OAuth2 support (#69)](https://travis-ci.org/ryanwinchester/hubspot-php/builds/169119334) fails. Could you please have look at it?

Is it v1.0.0-rc.4 stable and could it be used in production?

**Comment by ryanwinchester** [comment]
The tests haven't passed in a long time. There is no sandbox accounts or anything yet so it gets rate-limited or something by hubspot with the test credentials.

I am using it in production. (I don't use OAuth, though)
