### ISSUE TITLE
addContact should be post method in ContactList.php 

### ISSUE THREAD

**Issue by Tomek678** [ryanwinchester/hubspot-php#78]
public function addContact($list_id, $contact_ids)
    {
        $endpoint = "/contacts/v1/lists/{$list_id}/add";
        $options['json'] = ['vids' => $contact_ids];
  // here should be post not get
        return $this->request('get', $endpoint, $options);
    }

**Comment by ryanwinchester** [comment]
It is `"post"`

https://github.com/ryanwinchester/hubspot-php/blob/master/src/Resources/ContactLists.php#L162-L176
