### ISSUE TITLE
Error on GuzzleHttp/psr7 "Response could not be converted to int"

### ISSUE THREAD

**Issue by Xulai** [ryanwinchester/hubspot-php#81]
Hi there,
We're on Laravel 5.2 and we just updated from `v1.0.0-rc.4` to `v1.0.0` / https://github.com/ryanwinchester/hubspot-php/commit/93df25e8f29fa83440b78d9fdab285c49bf6 . Now when we try to update our hubspot contacts we're presented with this error below. We've had to revert back to `v1.0.0-rc.4` / https://github.com/ryanwinchester/hubspot-php/commit/c29461f3363ea320fc7a3a275644fc68c2696932 . Didn't see anything about this issue so  making one for it. 

The version of guzzlehttp/psr7 is `~1.3.1`. Using method Contacts->createOrUpdate

`[2017-01-25 15:52:25] local.ERROR: ErrorException: Object of class GuzzleHttp\Psr7\Response could not be converted to int in /var/www/api/vendor/guzzlehttp/psr7/src/Response.php:95
Stack trace:
#0 /var/www/api/vendor/guzzlehttp/psr7/src/Response.php(95): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Object of class...', '/var/www/api/ve...', 95, Array) 
#1 /var/www/api/vendor/ryanwinchester/hubspot-php/src/Http/Client.php(101): GuzzleHttp\Psr7\Response->__construct(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/api/vendor/ryanwinchester/hubspot-php/src/Resources/Contacts.php(46): SevenShores\Hubspot\Http\Client->request('post', 'https://api.hub...', Array)`

**Comment by Xulai** [comment]
Did a PR for what fixed my issue. It seemed to be "use"ing the wrong Response. It works fine when using the Response class in the same folder.

**Comment by flexgrip** [comment]
So wait... how do you fix this? Upgrade guzzle?

**Comment by flexgrip** [comment]
Never mind. I see what's going on. Problem is, composer is not updating for me yet. Should I be changing the version number to a different one?

**Comment by ayyobro** [comment]
I also found a quick fix for this. It was a matter of going to *ryanwinchester/hubspot-php/src/Http/Client.php*, and changing: 

`
// Change this line...
use GuzzleHttp\Psr7\Response;

// To this line
use SevenShores\Hubspot\Http\Response;

`

I really hate having to modify core package files like that, so I'm  hoping that this will be fixed in a patch soon?

If there's a better way to get around this than I've suggested, please let me know!

**Comment by skynet** [comment]
Has this been fixed in the core?

**Comment by ryanwinchester** [comment]
what version are you using?

**Comment by skynet** [comment]
latest
