### ISSUE TITLE
Get blogpost by pURL in addition to ID

### ISSUE THREAD

**Issue by wwwroth** [ryanwinchester/hubspot-php#92]
Currently using this lib to interface with our HubSpot account and I'm building the blog integration. With the blogPost resource you can only pull a single post by ID. I'd like to create a method to pull by pURL for friendly URLs on my end, and also when returning a post or multiple posts add a pURL field which is just `absolute_url` with the domain/dir stripped off.

If this is a one off and should be written on my end I'll pass but if you think it'd be a good addition I'll write it and submit a PR.

**Comment by ryanwinchester** [comment]
@wwwroth if it has an endpoint for this in the hubspot API, I'd gladly accept a PR.

If not, then I'd like to just keep the lib just for hitting the actual endpoints, and anything additional should be in your own projects.

**Comment by ryanwinchester** [comment]
feel free to re-open if it is the first case in my last comment 👍
