### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by P3zzl3** [ryanwinchester/hubspot-php#96]
Ryan, keen to speak to you about some additional development work on this API - or at least get your thoughts. Would it be possible we can talk please?
matthew.wheeler@bps-world.com
Thanks
Matt

**Comment by ryanwinchester** [comment]
Is it new endpoints you need added, or something else?

**Comment by P3zzl3** [comment]
Hi Ryan. Yup, new endpoints/all endpoints we can potentially. We're looking at pulling ALL data we can from hubspot.
Could you drop me a mail so I can contact you directly in email? : matthew.wheeler@bpa-world.com
